In [1]:
import pandas as pd
import torch

In [2]:
df = pd.read_csv('./data/af2_dataset_training_labeled.csv').drop('Unnamed: 0', axis=1)

In [3]:
bool_cols = [col for col in df.columns if df[col].dtype == bool]

In [4]:
df[bool_cols] = df[bool_cols].astype(int)

In [5]:
df

annotation_sequence  feat_A  feat_C  feat_D  feat_E  feat_F  feat_G  \
0                        M       0       0       0       0       0       0   
1                        G       0       0       0       0       0       1   
2                        Q       0       0       0       0       0       0   
3                        E       0       0       0       1       0       0   
4                        P       0       0       0       0       0       0   
...                    ...     ...     ...     ...     ...     ...     ...   
497161                   S       0       0       0       0       0       0   
497162                   H       0       0       0       0       0       0   
497163                   G       0       0       0       0       0       1   
497164                   G       0       0       0       0       0       1   
497165                   F       0       0       0       0       1       0   

        feat_H  feat_I  feat_K  ...  feat_DSSP_10  feat_DSSP_11  feat_DSSP_12  \
0            0       0       0  ...             0           0.0            47   
1            0       0       0  ...             0           0.0             0   
2            0       0       0  ...             1          -0.0            -1   
3            0       0       0  ...           706          -0.1           705   
4            0       0       0  ...             0           0.0           705   
...        ...     ...     ...  ...           ...           ...           ...   
497161       0       0       0  ...            -3          -0.1             2   
497162       1       0       0  ...          -358          -0.1          -330   
497163       0       0       0  ...          -360          -0.2            -1   
497164       0       0       0  ...             0           0.0             0   
497165       0       0       0  ...             0           0.0             0   

        feat_DSSP_13    coord_X    coord_Y    coord_Z        entry  \
0               -0.0 -26.499001  -4.742000 -35.189999  GEMI5_HUMAN   
1                0.0 -25.158001  -1.342000 -34.104000  GEMI5_HUMAN   
2               -0.0 -21.926001  -1.641000 -32.175999  GEMI5_HUMAN   
3               -0.0 -22.073999   0.654000 -29.171000  GEMI5_HUMAN   
4               -0.2 -19.783001   2.670000 -26.858999  GEMI5_HUMAN   
...              ...        ...        ...        ...          ...   
497161          -0.4 -19.742001  20.796000 -12.319000   AOC3_HUMAN   
497162          -0.1 -16.299000  19.153999 -12.640000   AOC3_HUMAN   
497163          -0.1 -13.404000  19.502001 -10.121000   AOC3_HUMAN   
497164           0.0 -10.986000  20.320000 -13.016000   AOC3_HUMAN   
497165           0.0  -7.456000  19.052999 -13.909000   AOC3_HUMAN   

        entry_index  y_Ligand  
0                 0         0  
1                 1         0  
2                 2         0  
3                 3         0  
4                 4         0  
...             ...       ...  
497161          755         0  
497162          756         0  
497163          757         0  
497164          758         0  
497165          759         0  

[497166 rows x 50 columns]

In [6]:
grouped = df.groupby('entry')

In [38]:
for entry, group in grouped:
    drop_cols = ['y_Ligand', 'annotation_sequence', 'annotation_atomrec', 'entry']
    x = group.loc[group['entry'] == entry, group.columns] \
        .sort_values(by='entry_index') \
        .drop(drop_cols, axis=1).values
    y = group['y_Ligand'].values
    edge_list = [group['entry_index'].values[:-1], group['entry_index'].values[1:]]

    x = torch.FloatTensor(x)
    y = torch.LongTensor(y)
    edge_list = torch.tensor(edge_list, dtype=torch.long)

    display(x)
    display(y)
    display(edge_list.T)
    break

tensor([[  0.0000,   0.0000,   0.0000,  ...,  28.6400,  14.4230,   0.0000],
        [  0.0000,   0.0000,   0.0000,  ...,  25.0730,  14.3910,   1.0000],
        [  0.0000,   0.0000,   0.0000,  ...,  23.0880,  12.2980,   2.0000],
        ...,
        [  1.0000,   0.0000,   0.0000,  ..., -25.1320, -20.9820, 240.0000],
        [  0.0000,   0.0000,   0.0000,  ..., -27.8010, -23.5450, 241.0000],
        [  0.0000,   0.0000,   0.0000,  ..., -27.9550, -27.0170, 242.0000]])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])

tensor([[  0,   1],
        [  1,   2],
        [  2,   3],
        [  3,   4],
        [  4,   5],
        [  5,   6],
        [  6,   7],
        [  7,   8],
        [  8,   9],
        [  9,  10],
        [ 10,  11],
        [ 11,  12],
        [ 12,  13],
        [ 13,  14],
        [ 14,  15],
        [ 15,  16],
        [ 16,  17],
        [ 17,  18],
        [ 18,  19],
        [ 19,  20],
        [ 20,  21],
        [ 21,  22],
        [ 22,  23],
        [ 23,  24],
        [ 24,  25],
        [ 25,  26],
        [ 26,  27],
        [ 27,  28],
        [ 28,  29],
        [ 29,  30],
        [ 30,  31],
        [ 31,  32],
        [ 32,  33],
        [ 33,  34],
        [ 34,  35],
        [ 35,  36],
        [ 36,  37],
        [ 37,  38],
        [ 38,  39],
        [ 39,  40],
        [ 40,  41],
        [ 41,  42],
        [ 42,  43],
        [ 43,  44],
        [ 44,  45],
        [ 45,  46],
        [ 46,  47],
        [ 47,  48],
        [ 48,  49],
        [ 49,  50],


In [1]:
from LigandBinaryDataset import LigandBinaryDataset

In [2]:
ds = LigandBinaryDataset('./data')

Processing...


['data\\raw\\af2_dataset_training_labeled.csv']
['data\\processed\\processed.dataset']


C:\Users\billb\OneDrive\Documents\Projects\CxC Cyclica\LigandBinaryDataset.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  C:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_new.cpp:204.)
  edge_list = torch.tensor(edge_list, dtype=torch.long)
Done!


In [10]:
ds

LigandBinaryDataset(723)

In [9]:
ds[0]

Data(x=[243, 46], edge_index=[2, 242], y=[243])

less goo!